# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Damon' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Damon
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  pod 'SwiftMessages'
  pod 'SQLite.swift', '~> 0.11.5'
  pod 'SkyFloatingLabelTextField'
  pod 'GoogleMaps'
  pod 'GooglePlaces'

end
